# Generated by Django 2.2.7 on 2020-05-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
