# Generated by Django 2.2.7 on 2020-05-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billing_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='billing',
            name='zipcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
