# Generated by Django 2.2.7 on 2020-05-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20200501_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='contact',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
