# Generated by Django 2.2.7 on 2020-05-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='occupation',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
