# Generated by Django 2.2.7 on 2020-03-11 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(null=True)),
                ('dp', models.ImageField(null=True, upload_to='profile')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('firstname', models.CharField(max_length=225, null=True)),
                ('lastname', models.CharField(max_length=225, null=True)),
                ('active', models.BooleanField(default=True)),
                ('number', models.CharField(max_length=12, null=True)),
                ('businesstype', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('admin', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('approve', models.BooleanField(default=False)),
                ('me', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], max_length=30, null=True)),
                ('affilates', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True)),
                ('sellingmethod', models.CharField(choices=[('wholesale', 'Wholesale'), ('Retail', 'Retail')], max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
