# Generated by Django 2.2.7 on 2020-04-28 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homeapp', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='incart',
            field=models.ManyToManyField(related_name='display', to='products.Tracker'),
        ),
        migrations.AddField(
            model_name='activity',
            name='pdincart',
            field=models.ManyToManyField(related_name='pdcart', to='products.Product'),
        ),
        migrations.AddField(
            model_name='activity',
            name='popular',
            field=models.ManyToManyField(related_name='popularproduct', to='products.Product'),
        ),
        migrations.AddField(
            model_name='activity',
            name='products',
            field=models.ManyToManyField(related_name='products', to='products.Product'),
        ),
        migrations.AddField(
            model_name='activity',
            name='removeincart',
            field=models.ManyToManyField(related_name='removecart', to='products.Product'),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='me',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
