# Generated by Django 2.2.7 on 2020-04-28 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_auto_20200428_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shippingaddress', to='homeapp.Sessionlog'),
        ),
    ]
