# Generated by Django 2.2.7 on 2020-05-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_auto_20200428_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerid',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
