# Generated by Django 2.2.7 on 2020-03-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_premium_tryperiod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tryperiod',
            old_name='state',
            new_name='active',
        ),
    ]
