# Generated by Django 2.2.7 on 2020-05-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_sagreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerid',
            name='idnum',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
