# Generated by Django 2.2.7 on 2020-03-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_auto_20200321_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership',
            field=models.CharField(choices=[('Per Sale', 'Pay Sale'), ('Subscription', 'Subscription')], max_length=30, null=True),
        ),
    ]
