# Generated by Django 2.2.7 on 2020-05-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_auto_20200518_2055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sagreement',
            new_name='Sellertermsandcondition',
        ),
    ]
