# Generated by Django 2.2.7 on 2020-03-28 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0009_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
