# Generated by Django 2.2.7 on 2020-05-19 12:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0009_auto_20200519_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer_terms_and_condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', ckeditor.fields.RichTextField(null=True)),
            ],
        ),
    ]
