# Generated by Django 2.2.7 on 2020-05-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0011_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='detail',
            field=models.TextField(null=True),
        ),
    ]
