# Generated by Django 2.2.7 on 2020-04-08 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0012_auto_20200408_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='session',
        ),
        migrations.DeleteModel(
            name='Tracker',
        ),
    ]
