# Generated by Django 2.2.7 on 2020-04-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0013_auto_20200408_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='session',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
