# Generated by Django 2.2.7 on 2020-04-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0014_activity_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
