# Generated by Django 2.2.7 on 2020-04-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20200408_0942'),
        ('homeapp', '0015_delete_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=200, null=True)),
                ('display', models.ManyToManyField(related_name='display', to='products.Tracker')),
                ('products', models.ManyToManyField(related_name='products', to='products.Tracker')),
            ],
        ),
    ]
