# Generated by Django 2.2.7 on 2020-04-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0016_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='products',
            field=models.ManyToManyField(related_name='products', to='products.Product'),
        ),
    ]
