# Generated by Django 2.2.7 on 2020-04-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20200412_0158'),
        ('homeapp', '0017_auto_20200408_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='pdincart',
            field=models.ManyToManyField(related_name='pdcart', to='products.Product'),
        ),
    ]
