# Generated by Django 2.2.7 on 2020-04-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0018_activity_pdincart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='pdincart',
            new_name='pdnotincart',
        ),
    ]
