# Generated by Django 2.2.7 on 2020-04-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0022_auto_20200421_0448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='pdnotincart',
            new_name='pdincart',
        ),
    ]
