# Generated by Django 2.2.7 on 2020-05-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
