# Generated by Django 2.2.7 on 2020-05-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200501_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='transactioncode',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
