# Generated by Django 2.2.7 on 2020-05-03 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_orderstate'),
        ('order', '0003_productorder_transactioncode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productorderid', models.CharField(max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('state', models.CharField(choices=[('Sold', 'Sold'), ('Refunded', 'Refunded'), ('available', 'available')], max_length=100, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('productorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.ProductOrder')),
            ],
        ),
    ]
