# Generated by Django 2.2.7 on 2020-05-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200503_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='reason',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
