# Generated by Django 2.2.7 on 2020-05-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20200503_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborder',
            name='reason',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='state',
            field=models.CharField(choices=[('sold', 'sold'), ('refunded', 'refunded'), ('available', 'available'), ('cancelled', 'cancelled')], default='pending', max_length=100),
        ),
    ]
