# Generated by Django 2.2.7 on 2020-05-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20200503_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='suborder',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
