# Generated by Django 2.2.7 on 2020-05-03 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeapp', '0003_auto_20200428_0701'),
        ('order', '0008_auto_20200503_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suborder',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homeapp.Sessionlog'),
        ),
    ]
