# Generated by Django 2.2.7 on 2020-05-03 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20200503_0419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suborder',
            old_name='session',
            new_name='buyer',
        ),
    ]
