# Generated by Django 2.2.7 on 2020-05-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20200503_0421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productorder',
            old_name='session',
            new_name='buyer',
        ),
    ]
