# Generated by Django 2.2.7 on 2020-05-05 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200504_1219'),
        ('order', '0011_auto_20200503_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='orderinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.CostProcessing'),
        ),
    ]
