# Generated by Django 2.2.7 on 2020-05-06 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20200505_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborder',
            name='productorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suborder', to='order.ProductOrder'),
        ),
    ]
