# Generated by Django 2.2.7 on 2020-05-06 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_auto_20200428_0701'),
        ('order', '0015_auto_20200505_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiversName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('contact', models.IntegerField(null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homeapp.Sessionlog')),
            ],
        ),
    ]
