# Generated by Django 2.2.7 on 2020-05-06 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_receiversname'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiversname',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.ProductOrder'),
        ),
    ]
