# Generated by Django 2.2.7 on 2020-05-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_receiversname_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborder',
            name='state',
            field=models.CharField(choices=[('sold', 'sold'), ('refunded', 'refunded'), ('notavailable', 'not available'), ('cancelled', 'cancelled')], default='processing', max_length=100),
        ),
    ]
