# Generated by Django 2.2.7 on 2020-05-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20200506_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='commets',
            field=models.TextField(null=True),
        ),
    ]
