# Generated by Django 2.2.7 on 2020-05-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_auto_20200507_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiversname',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
