# Generated by Django 2.2.7 on 2020-05-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_auto_20200507_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborder',
            name='state',
            field=models.CharField(choices=[('sold', 'sold'), ('refunded', 'refunded'), ('processing', 'processing'), ('cancelled', 'cancelled')], default='processing', max_length=100),
        ),
    ]
