# Generated by Django 2.2.7 on 2020-05-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_auto_20200507_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='calls',
            field=models.IntegerField(default=0),
        ),
    ]
