# Generated by Django 2.2.7 on 2020-04-01 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('descrip', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('productname', models.CharField(max_length=50, null=True)),
                ('picone', models.ImageField(blank=True, null=True, upload_to='productimage')),
                ('pictwo', models.ImageField(blank=True, null=True, upload_to='productimage')),
                ('picthree', models.ImageField(blank=True, null=True, upload_to='productimage')),
                ('picfour', models.ImageField(blank=True, null=True, upload_to='productimage')),
                ('descript', models.TextField(null=True)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('model', models.CharField(max_length=100, null=True)),
                ('size', models.CharField(max_length=100, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('posted', 'posted'), ('pending', 'pending'), ('sold', 'sold')], default='pending', max_length=200, null=True)),
                ('state', models.CharField(choices=[('Brand New', 'Brand New'), ('Used', 'Used')], max_length=200, null=True)),
                ('uniqueid', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('sales', models.IntegerField(choices=[(0, 0), (20, 20), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (60, 60), (70, 70), (80, 80)], default=0)),
                ('pdprice', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('salesprice', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='products.Category')),
                ('colorid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_id', to='products.Product')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_subcategory', to='products.SubCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userproduct', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CostProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('costaftersales', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('pdcount', models.IntegerField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(related_name='cpds', to='products.CostProcessing')),
            ],
        ),
    ]
