# Generated by Django 2.2.7 on 2020-04-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colorid',
        ),
    ]
