# Generated by Django 2.2.7 on 2020-04-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
