# Generated by Django 2.2.7 on 2020-05-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200429_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orderstate',
            field=models.CharField(choices=[('Sold', 'Sold'), ('Refunded', 'Refunded'), ('available', 'available')], default='available', max_length=200),
        ),
    ]
