# Generated by Django 2.2.7 on 2020-04-01 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_colorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdcolor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_id', to='products.Product'),
        ),
    ]
