# Generated by Django 2.2.7 on 2020-04-01 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_pdcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdcolor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_id', to='products.Product'),
        ),
    ]
