# Generated by Django 2.2.7 on 2020-05-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200503_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='orderstate',
            field=models.CharField(choices=[('sold', 'sold'), ('Refunded', 'Refunded'), ('available', 'available'), ('cancelled', 'cancelled')], default='available', max_length=200),
        ),
    ]
