# Generated by Django 2.2.7 on 2020-05-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200503_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='orderstate',
            field=models.CharField(choices=[('sold', 'sold'), ('refunded', 'refunded'), ('available', 'available'), ('cancelled', 'cancelled')], default='available', max_length=200),
        ),
    ]
