# Generated by Django 2.2.7 on 2020-04-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200401_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productsize',
            name='pricechange',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productsize',
            name='sizeprice',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productsize',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
