# Generated by Django 2.2.7 on 2020-04-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200401_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availableseizes',
            field=models.ManyToManyField(null=True, related_name='avlprice', to='products.ProductSize'),
        ),
    ]
