# Generated by Django 2.2.7 on 2020-05-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_instock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='instock',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
