# Generated by Django 2.2.7 on 2020-03-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('Brand New', 'Brand New'), ('Used', 'Used')], max_length=200, null=True),
        ),
    ]
