# Generated by Django 2.2.7 on 2020-03-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picfour',
            field=models.ImageField(blank=True, null=True, upload_to='productimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picone',
            field=models.ImageField(blank=True, null=True, upload_to='productimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picthree',
            field=models.ImageField(blank=True, null=True, upload_to='productimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pictwo',
            field=models.ImageField(blank=True, null=True, upload_to='productimage'),
        ),
    ]
