# Generated by Django 2.2.7 on 2020-05-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200505_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availableseizes',
            field=models.ManyToManyField(blank=True, null=True, related_name='avlprice', to='products.ProductSize'),
        ),
    ]
