# Generated by Django 2.2.7 on 2020-03-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200323_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='approve',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('sold', 'sold')], default='pending', max_length=200, null=True),
        ),
    ]
