# Generated by Django 2.2.7 on 2020-03-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200325_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uniqueid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
