# Generated by Django 2.2.7 on 2020-05-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200507_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('posted', 'posted'), ('pending', 'pending')], default='pending', max_length=200, null=True),
        ),
    ]
