# Generated by Django 2.2.7 on 2020-05-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200508_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending')], default='pending', max_length=200, null=True),
        ),
    ]
