# Generated by Django 2.2.7 on 2020-04-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200402_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='sizeprice',
            field=models.IntegerField(null=True),
        ),
    ]
