# Generated by Django 2.2.7 on 2020-03-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_uniqueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.IntegerField(choices=[(0, 0), (20, 20), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (60, 60), (70, 70), (80, 80)], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('posted', 'posted'), ('pending', 'pending'), ('sold', 'sold')], default='pending', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='uniqueid',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
