# Generated by Django 2.2.7 on 2020-04-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200402_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picfour',
            field=models.ImageField(null=True, upload_to='productimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picone',
            field=models.ImageField(null=True, upload_to='productimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picthree',
            field=models.ImageField(null=True, upload_to='productimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pictwo',
            field=models.ImageField(null=True, upload_to='productimage'),
        ),
    ]
