# Generated by Django 2.2.7 on 2020-05-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_sellerid_verified'),
        ('products', '0013_productreques'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductReques',
            new_name='ProductRequest',
        ),
    ]
