# Generated by Django 2.2.7 on 2020-03-28 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200327_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('salesprice', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='status',
            name='user',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
