# Generated by Django 2.2.7 on 2020-03-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200327_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costprocessing',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='salesprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
