# Generated by Django 2.2.7 on 2020-04-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200402_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdcolor',
            field=models.ManyToManyField(blank=True, null=True, related_name='color_id', to='products.ProductColor'),
        ),
    ]
