# Generated by Django 2.2.7 on 2020-03-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200327_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costprocessing',
            old_name='salesprice',
            new_name='costaftersales',
        ),
        migrations.AlterField(
            model_name='product',
            name='pdprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='salesprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
