# Generated by Django 2.2.7 on 2020-04-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_pdcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
