# Generated by Django 2.2.7 on 2020-04-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_productcolor_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='slug',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
