# Generated by Django 2.2.7 on 2020-03-29 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0016_auto_20200329_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='costprocessing',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('products', models.ManyToManyField(related_name='cpds', to='products.CostProcessing')),
            ],
        ),
    ]
