# Generated by Django 2.2.7 on 2020-04-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20200405_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='sizeprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
