# Generated by Django 2.2.7 on 2020-04-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20200405_0410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costprocessing',
            old_name='user',
            new_name='owner',
        ),
    ]
