# Generated by Django 2.2.7 on 2020-03-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_cart_pdcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='salesprice',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
