# Generated by Django 2.2.7 on 2020-05-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20200515_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='categoryname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='subcategoryslug',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
