# Generated by Django 2.2.7 on 2020-03-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200331_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdprice',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='salesprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
