# Generated by Django 2.2.7 on 2020-04-08 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200406_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.BooleanField(default=False)),
                ('productdisplay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='products.Product')),
            ],
        ),
    ]
