# Generated by Django 2.2.7 on 2020-05-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20200517_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='productname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='productprice',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='productstate',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
