# Generated by Django 2.2.7 on 2020-04-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20200408_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='session',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
