# Generated by Django 2.2.7 on 2020-04-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20200408_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='pdcount',
            field=models.IntegerField(default='0'),
        ),
    ]
