# Generated by Django 2.2.7 on 2020-04-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20200412_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='productcart',
            field=models.BooleanField(default=False),
        ),
    ]
