# Generated by Django 2.2.7 on 2020-04-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_tracker_productcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='productcart',
            new_name='productincart',
        ),
    ]
