# Generated by Django 2.2.7 on 2020-04-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20200414_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
